@baseUrl = http://localhost:5100/api/v1

GET {{baseUrl}}/todos

###

GET {{baseUrl}}/todos/2

###

POST {{baseUrl}}/todos
Content-Type: application/json

{
    "title": "Izes mi carape",
    "description": "Svakog dana treba izesti carape."
}

###

PUT {{baseUrl}}/todos/2
Content-Type: application/json

{
    "title": "Izes mi carape",
    "description": "Svakog dana treba izesti carape.",
    "isCompleted": true,
    "completedAt": "2024-06-02"
}  

###

PATCH {{baseUrl}}/todos/1/complete
Content-Type: application/json

{
    "isComplete": false
}

###

DELETE {{baseUrl}}/todos/1
