@baseUrl = http://localhost:5100/api/v1/users

GET {{baseUrl}}/

###

POST {{baseUrl}}/
Content-Type: application/json

{
  "username": "djoka",
  "password": "Tandrcak"
}

###

DELETE {{baseUrl}}/1

###

POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "Bartholome26",
  "password": "senegal"
}